name: Building Resume CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make build.sh executable
      run: chmod +x build.sh
    
    - name: Build the Docker image
      run: docker build -t resume-builder .

    - name: Run build scritt
      run: docker run --rm -v ${{ github.workspace }}:/cv resume-builder

    - name: Upload built PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: ./main.pdf
